name: CI

on:
  push:
    branches: [workflow-check]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name : Set output vars
        id: vars  
        run: |
            echo BUILD_NUMBER=$(date '+%Y%H%M%S') >> $GITHUB_ENV 
      - name: Build Image
        run: |
          VERSION=$(cat ./version.sh)
          docker build . --file Dockerfile --tag docker_nginx:$VERSION.${{ env.BUILD_NUMBER }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dockernginx
          #IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:v$VERSION.${{ env.BUILD_NUMBER }}